// Generated by mail-core generate-types (ts-rs). Do not edit.
// Contract: docs/vertical-slice-01.md — camelCase fields, snake_case discriminants.

export const LIST_CONVERSATIONS_COMMAND = 'list_conversations';
export const GET_CONVERSATION_COMMAND = 'get_conversation';
export const SET_ARCHIVED_COMMAND = 'set_archived';
export const MAILBOX_CHANGED_EVENT = 'mailbox_changed';

export type ConversationRef = { accountId: string, conversationId: string, };

export type Address = { 
/**
 * Absent display name serializes as `null`.
 */
displayName: string | null, mailbox: string, };

export type OperationStatus = "queued" | "applying" | "confirmed" | "failed";

export type OperationFailure = { "kind": "provider_unavailable" } | { "kind": "provider_rejected" };

export type MailError = { "kind": "not_found" } | { "kind": "invalid_request", 
/**
 * Name of the offending request field (camelCase DTO name).
 */
field: string, } | { "kind": "request_id_conflict" } | { "kind": "storage_unavailable" } | { "kind": "profile_in_use" };

export type OperationReceipt = { operationId: string, acceptedAt: string, };

export type SetArchived = { conversation: ConversationRef, archived: boolean, requestId: string, };

export type ConversationSummary = { ref: ConversationRef, subject: string, participants: Array<Address>, 
/**
 * Plain-text preview derived from the newest message body.
 */
preview: string, lastMessageAt: string, pendingOperationId: string | null, };

export type Message = { id: string, from: Address, to: Array<Address>, sentAt: string, 
/**
 * Literal fixture text; hostile markup is data, never rendered.
 */
bodyText: string, };

export type Conversation = { ref: ConversationRef, subject: string, messages: Array<Message>, 
/**
 * Effective inbox membership (cached provider facts + pending overlay).
 */
isInInbox: boolean, 
/**
 * Newest queued/applying operation id, if any.
 */
pendingOperationId: string | null, };

export type OperationSummary = { id: string, conversation: ConversationRef, requestedArchived: boolean, status: OperationStatus, 
/**
 * `null` unless the operation failed definitely.
 */
failure: OperationFailure | null, };

export type InboxSnapshot = { 
/**
 * Conversations in the effective inbox, newest message first.
 */
conversations: Array<ConversationSummary>, 
/**
 * Persisted operations, newest acceptance first.
 */
activity: Array<OperationSummary>, };

